# Generated by Django 2.2.6 on 2020-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JKapp', '0002_auto_20200111_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='JKapp/images'),
        ),
    ]
