# Generated by Django 2.2 on 2020-03-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JKapp', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
