# Generated by Django 2.2 on 2020-03-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JKapp', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
