# Generated by Django 2.2 on 2020-03-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JKapp', '0006_auto_20200310_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
