# Generated by Django 2.2 on 2020-03-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JKapp', '0007_auto_20200310_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
